import { Product, ProductPackaging, StockMovement } from '../types';

// Helper to generate clean bakery SVG placeholder data URIs
function makeSvgDataUri(name: string, bg: string, emoji: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300" viewBox="0 0 300 300">
    <rect width="300" height="300" rx="36" fill="${bg}"/>
    <text x="150" y="140" font-size="80" text-anchor="middle" dominant-baseline="middle">${emoji}</text>
    <text x="150" y="220" font-size="22" font-weight="bold" fill="#ffffff" text-anchor="middle" font-family="sans-serif">${name}</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

const NOW = new Date().toISOString();
const TODAY_EARLIER = new Date(Date.now() - 3600 * 4000).toISOString();
const YESTERDAY = new Date(Date.now() - 3600 * 24000).toISOString();

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'PRD-001',
    name: 'Tepung Terigu Segitiga Biru',
    category: 'Tepung',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PRD-002',
    name: 'Butter Anchor Salted',
    category: 'Butter & Margarine',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PRD-003',
    name: 'Gula Pasir Gulaku',
    category: 'Gula',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PRD-004',
    name: 'Coklat Bubuk Bendico',
    category: 'Coklat',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PRD-005',
    name: 'Susu Bubuk Full Cream NZMP',
    category: 'Susu',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PRD-006',
    name: 'Telur Ayam Fresh',
    category: 'Telur',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
];

export const SEED_PACKAGINGS: ProductPackaging[] = [
  // 1. Tepung Terigu
  {
    id: 'PKG-001',
    productId: 'PRD-001',
    productCode: 'TPG-ORI-001',
    type: 'ORIGINAL',
    packageSize: 25,
    packageUnit: 'kg',
    stock: 3,
    minimumStock: 1,
    image: makeSvgDataUri('Tepung Karung', '#2563EB', '🌾'),
    purchasePrice: 285000,
    supplier: 'Bogasari Distributor',
    location: 'Gudang Utama - Rak A1',
    barcode: '8991234500011',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PKG-002',
    productId: 'PRD-001',
    productCode: 'TPG-RP-1K',
    type: 'REPACK',
    packageSize: 1,
    packageUnit: 'kg',
    stock: 12,
    minimumStock: 5,
    image: makeSvgDataUri('Tepung 1kg', '#3B82F6', '📦'),
    purchasePrice: 12500,
    supplier: 'Internal Toko',
    location: 'Etalase Depan - Rak B2',
    barcode: '8991234500012',
    createdAt: YESTERDAY,
    updatedAt: TODAY_EARLIER,
  },
  {
    id: 'PKG-003',
    productId: 'PRD-001',
    productCode: 'TPG-RP-500',
    type: 'REPACK',
    packageSize: 500,
    packageUnit: 'gram',
    stock: 20,
    minimumStock: 5,
    image: makeSvgDataUri('Tepung 500g', '#60A5FA', '🥖'),
    purchasePrice: 6500,
    supplier: 'Internal Toko',
    location: 'Etalase Depan - Rak B2',
    barcode: '8991234500013',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },

  // 2. Butter
  {
    id: 'PKG-004',
    productId: 'PRD-002',
    productCode: 'BUT-ORI-001',
    type: 'ORIGINAL',
    packageSize: 10,
    packageUnit: 'kg',
    stock: 2,
    minimumStock: 1,
    image: makeSvgDataUri('Butter Box', '#D97706', '🧈'),
    purchasePrice: 1350000,
    supplier: 'Fonterra Dairy Indonesia',
    location: 'Chiller Ruang 1',
    barcode: '8991234500021',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PKG-005',
    productId: 'PRD-002',
    productCode: 'BUT-RP-500',
    type: 'REPACK',
    packageSize: 500,
    packageUnit: 'gram',
    stock: 2,
    minimumStock: 5, // MENIPIS
    image: makeSvgDataUri('Butter 500g', '#F59E0B', '🧈'),
    purchasePrice: 72000,
    supplier: 'Internal Toko',
    location: 'Chiller Display Depan',
    barcode: '8991234500022',
    createdAt: YESTERDAY,
    updatedAt: TODAY_EARLIER,
  },

  // 3. Gula Pasir
  {
    id: 'PKG-006',
    productId: 'PRD-003',
    productCode: 'GUL-ORI-001',
    type: 'ORIGINAL',
    packageSize: 50,
    packageUnit: 'kg',
    stock: 4,
    minimumStock: 1,
    image: makeSvgDataUri('Gula Karung', '#059669', '🍬'),
    purchasePrice: 720000,
    supplier: 'PT Sugar Group',
    location: 'Gudang Utama - Pallet C',
    barcode: '8991234500031',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PKG-007',
    productId: 'PRD-003',
    productCode: 'GUL-RP-1K',
    type: 'REPACK',
    packageSize: 1,
    packageUnit: 'kg',
    stock: 25,
    minimumStock: 10,
    image: makeSvgDataUri('Gula 1kg', '#10B981', '🧁'),
    purchasePrice: 15500,
    supplier: 'Internal Toko',
    location: 'Etalase Depan - Rak A3',
    barcode: '8991234500032',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },

  // 4. Coklat Bubuk
  {
    id: 'PKG-008',
    productId: 'PRD-004',
    productCode: 'CB-ORI-001',
    type: 'ORIGINAL',
    packageSize: 5,
    packageUnit: 'kg',
    stock: 0, // HABIS
    minimumStock: 2,
    image: makeSvgDataUri('Coklat Zak', '#78350F', '🍫'),
    purchasePrice: 480000,
    supplier: 'Cocoa Indo Utama',
    location: 'Gudang Utama - Rak D1',
    barcode: '8991234500041',
    createdAt: YESTERDAY,
    updatedAt: TODAY_EARLIER,
  },
  {
    id: 'PKG-009',
    productId: 'PRD-004',
    productCode: 'CB-RP-250',
    type: 'REPACK',
    packageSize: 250,
    packageUnit: 'gram',
    stock: 15,
    minimumStock: 5,
    image: makeSvgDataUri('Coklat 250g', '#92400E', '🍫'),
    purchasePrice: 28000,
    supplier: 'Internal Toko',
    location: 'Etalase Depan - Rak D2',
    barcode: '8991234500042',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },

  // 5. Susu Bubuk
  {
    id: 'PKG-010',
    productId: 'PRD-005',
    productCode: 'SUS-ORI-001',
    type: 'ORIGINAL',
    packageSize: 25,
    packageUnit: 'kg',
    stock: 1, // MENIPIS
    minimumStock: 2,
    image: makeSvgDataUri('Susu Karung', '#0284C7', '🥛'),
    purchasePrice: 1850000,
    supplier: 'Global Dairy Import',
    location: 'Gudang Utama - Rak E1',
    barcode: '8991234500051',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    id: 'PKG-011',
    productId: 'PRD-005',
    productCode: 'SUS-RP-500',
    type: 'REPACK',
    packageSize: 500,
    packageUnit: 'gram',
    stock: 8,
    minimumStock: 4,
    image: makeSvgDataUri('Susu 500g', '#38BDF8', '🥛'),
    purchasePrice: 42000,
    supplier: 'Internal Toko',
    location: 'Etalase Depan - Rak E2',
    barcode: '8991234500052',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },

  // 6. Telur Ayam
  {
    id: 'PKG-012',
    productId: 'PRD-006',
    productCode: 'TLR-ORI-001',
    type: 'ORIGINAL',
    packageSize: 15,
    packageUnit: 'kg',
    stock: 6,
    minimumStock: 2,
    image: makeSvgDataUri('Telur Tray', '#E11D48', '🥚'),
    purchasePrice: 390000,
    supplier: 'Peternakan Berkah Blitar',
    location: 'Ruang Telur Suhu Ruang',
    barcode: '8991234500061',
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
];

export const SEED_MOVEMENTS: StockMovement[] = [
  {
    id: 'MOV-001',
    productId: 'PRD-001',
    packagingId: 'PKG-001',
    productCode: 'TPG-ORI-001',
    type: 'IN',
    quantity: 3,
    unit: 'karung',
    stockBefore: 0,
    stockAfter: 3,
    note: 'Restock supplier Bogasari',
    createdAt: YESTERDAY,
  },
  {
    id: 'MOV-002',
    productId: 'PRD-001',
    packagingId: 'PKG-001',
    productCode: 'TPG-ORI-001',
    type: 'REPACK_OUT',
    quantity: 10,
    unit: 'kg',
    stockBefore: 3,
    stockAfter: 3, // Repack dari karung terbuka
    relatedMovementId: 'MOV-003',
    note: 'Repack harian ke kemasan 1kg',
    createdAt: TODAY_EARLIER,
  },
  {
    id: 'MOV-003',
    productId: 'PRD-001',
    packagingId: 'PKG-002',
    productCode: 'TPG-RP-1K',
    type: 'REPACK_IN',
    quantity: 10,
    unit: 'pack',
    stockBefore: 2,
    stockAfter: 12,
    relatedMovementId: 'MOV-002',
    note: 'Hasil repack dari TPG-ORI-001',
    createdAt: TODAY_EARLIER,
  },
  {
    id: 'MOV-004',
    productId: 'PRD-002',
    packagingId: 'PKG-005',
    productCode: 'BUT-RP-500',
    type: 'OUT',
    quantity: 3,
    unit: 'pack',
    stockBefore: 5,
    stockAfter: 2,
    note: 'Dipakai pesanan kue bolu pandan',
    createdAt: TODAY_EARLIER,
  },
  {
    id: 'MOV-005',
    productId: 'PRD-004',
    packagingId: 'PKG-008',
    productCode: 'CB-ORI-001',
    type: 'OUT',
    quantity: 1,
    unit: 'pack',
    stockBefore: 1,
    stockAfter: 0,
    note: 'Dipakai produksi brownies kukus',
    createdAt: NOW,
  },
];
